<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->insert([
            [
                'name' => 'Baby Bouncer Chair',
                'description' => 'Kursi bouncer bayi yang ringan dan nyaman, cocok untuk bayi bersantai atau tidur dengan aman. Terbuat dari bahan berkualitas, mudah dilipat, dan memiliki desain ergonomis yang mendukung postur bayi.',
                'price' => 150000,
                'image_path' => 'images/p1.png',
                'category' => 'perlengkapan_lain',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baby Stroller',
                'description' => 'Kereta dorong bayi yang praktis dan modern, dilengkapi dengan kanopi pelindung matahari, sabuk pengaman, serta roda yang mudah dikendalikan. Cocok untuk berjalan-jalan dengan bayi dan memberikan kenyamanan ekstra.',
                'price' => 600000,
                'image_path' => 'images/p2.png',
                'category' => 'perlengkapan_lain',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baby Play Mat with Arch Toys',
                'description' => 'Playmat bayi dengan lengkungan mainan gantung yang menarik, dirancang untuk merangsang perkembangan sensorik dan motorik bayi. Bahan lembut dan aman, ideal untuk bermain dan tummy time.',
                'price' => 250000,
                'image_path' => 'images/p3.png',
                'category' => 'mainan',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baby Walker with Activity Toys',
                'description' => 'Baby walker multifungsi dengan mainan edukatif yang membantu bayi belajar berjalan sambil bermain. Dilengkapi dengan roda halus, pegangan ergonomis, dan permainan interaktif untuk melatih koordinasi.',
                'price' => 300000,
                'image_path' => 'images/p4.png',
                'category' => 'mainan',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Classic Baby Crib',
                'description' => 'Ranjang bayi klasik dengan desain kokoh dan material kayu berkualitas. Aman, nyaman, dan ideal untuk bayi tidur nyenyak. Cocok untuk kamar tidur minimalis.',
                'price' => 1200000,
                'image_path' => 'images/p5.png',
                'category' => 'perlengkapan_tidur',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baby Rocker Bassinet',
                'description' => 'Tempat tidur goyang bayi yang nyaman dan portable. Dilengkapi mainan gantung dan desain ergonomis untuk membuat bayi tidur lebih nyenyak.',
                'price' => 700000,
                'image_path' => 'images/p6.png',
                'category' => 'perlengkapan_tidur',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Moon Shaped Wooden Cradle',
                'description' => 'Buaian bayi berbentuk bulan yang unik dengan desain modern dan elegan. Terbuat dari material kayu berkualitas tinggi dan aman untuk bayi.',
                'price' => 1500000,
                'image_path' => 'images/p7.png',
                'category' => 'perlengkapan_tidur',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baby Onesie Pajamas',
                'description' => 'Piyama bayi berbahan katun lembut dan breathable. Nyaman dipakai untuk tidur atau bermain. Desain lucu dengan motif yang menarik.',
                'price' => 100000,
                'image_path' => 'images/p8.png',
                'category' => 'baju',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baby Girl Dress',
                'description' => 'Gaun cantik untuk bayi perempuan dengan desain lucu dan bahan lembut yang nyaman dipakai. Cocok untuk acara santai atau spesial.',
                'price' => 120000,
                'image_path' => 'images/p9.png',
                'category' => 'baju',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Baby Romper Set',
                'description' => 'Set jumper bayi dengan atasan dan bawahan berbahan katun berkualitas. Desain cerah dan menarik, cocok untuk bermain atau bepergian.',
                'price' => 130000,
                'image_path' => 'images/p10.png',
                'category' => 'baju',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bodysuit Bayi Toy Story',
                'description' => 'Bodysuit bayi berbahan katun lembut dengan desain karakter Toy Story yang lucu. Cocok untuk bayi laki-laki yang aktif dan menyukai petualangan. Dilengkapi dengan kancing bahu untuk memudahkan saat mengganti popok.',
                'price' => 75000,
                'image_path' => 'images/p11.jpeg',
                'category' => 'baju',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Romper Bayi Motif Binatang',
                'description' => 'Romper bayi berbahan katun organik yang nyaman dan lembut di kulit bayi. Desain motif binatang yang lucu dan warna pastel yang lembut membuat bayi terlihat semakin menggemaskan.',
                'price' => 90000,
                'image_path' => 'images/p12.png',
                'category' => 'baju',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Setelan Bayi Motif Buah-buahan',
                'description' => 'Setelan bayi yang terdiri dari atasan lengan panjang dan celana panjang. Bahan katun yang lembut dan menyerap keringat membuat bayi nyaman sepanjang hari. Desain motif buah-buahan yang ceria cocok untuk bayi yang aktif.',
                'price' => 120000,
                'image_path' => 'images/p13.png',
                'category' => 'baju',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dress Bayi Motif Hewan',
                'description' => 'Dress bayi berbahan katun dengan desain motif hewan yang lucu dan detail renda yang cantik. Cocok untuk acara istimewa atau sehari-hari. Dilengkapi dengan tali sleting di belakang untuk memudahkan saat memakaikan.',
                'price' => 100000,
                'image_path' => 'images/p14.png',
                'category' => 'baju',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dress Bayi Motif Bunga',
                'description' => 'Dress bayi berbahan katun dengan desain motif bunga yang cantik dan warna pastel yang lembut. Cocok untuk bayi perempuan yang suka tampil manis. Roknya yang berlapis membuat bayi terlihat lebih berisi.',
                'price' => 85000,
                'image_path' => 'images/p15.png',
                'category' => 'baju',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Walker Bayi Bermusik',
                'description' => 'Walker bayi yang dilengkapi dengan berbagai mainan interaktif seperti piano, lampu warna-warni, dan suara-suara lucu untuk merangsang perkembangan motorik dan sensorik bayi. Desain yang menarik dan warna-warni akan membuat bayi semakin senang bermain.',
                'price' => 600000,
                'image_path' => 'images/p16.png',
                'category' => 'mainan',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Mainan Bayi Hutan Ajaib',
                'description' => 'Activity gym dengan desain hutan yang penuh warna, dilengkapi dengan berbagai mainan gantung seperti boneka binatang, cermin, dan mainan yang bertekstur. Sempurna untuk merangsang penglihatan, pendengaran, dan sentuhan bayi.',
                'price' => 450000,
                'image_path' => 'images/p17.jpeg',
                'category' => 'mainan',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ayunan Bayi Elektrik',
                'description' => 'Ayunan bayi yang dapat diatur kecepatan dan sudut kemiringannya. Dilengkapi dengan fitur vibrasi menenangkan dan suara-suara alam yang menenangkan. Desain ringkas dan mudah dilipat.',
                'price' => 750000,
                'image_path' => 'images/p18.png',
                'category' => 'mainan',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tumpuk Cincin Pelangi',
                'description' => 'Mainan edukasi klasik yang membantu melatih motorik halus bayi. Terdiri dari cincin-cincin berwarna-warni dengan ukuran berbeda yang dapat ditumpuk.',
                'price' => 120000,
                'image_path' => 'images/p19.png',
                'category' => 'mainan',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kotak Mainan Sortir',
                'description' => 'Kotak mainan yang berisi berbagai bentuk hewan dengan warna-warni. Bayi dapat belajar mengenal bentuk dan warna sambil memasukkan bentuk yang sesuai ke dalam lubang yang disediakan.',
                'price' => 180000,
                'image_path' => 'images/p20.png',
                'category' => 'mainan',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kotak Mainan Balok Kayu',
                'description' => 'Kotak mainan yang berisi balok kayu dengan berbagai ukuran dan bentuk. Termasuk ember untuk memudahkan penyimpanan. Cocok untuk mengembangkan kreativitas dan imajinasi anak.',
                'price' => 250000,
                'image_path' => 'images/p21.png',
                'category' => 'mainan',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bedong Bayi Motif Bintang',
                'description' => 'Bedong bayi berbahan katun organik yang lembut dan nyaman di kulit bayi. Desain motif bintang yang menenangkan dan warna pastel yang lembut menciptakan suasana tidur yang nyaman bagi bayi.',
                'price' => 150000,
                'image_path' => 'images/p22.png',
                'category' => 'perlengkapan_tidur',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bantal Bayi Bentuk U',
                'description' => 'Bantal bayi berbentuk U yang mendukung posisi kepala dan leher bayi saat tidur. Terbuat dari bahan katun lembut dan diisi dengan dakron yang empuk. Desain motif hewan yang lucu membuat bantal ini semakin menarik.',
                'price' => 120000,
                'image_path' => 'images/p23.png',
                'category' => 'perlengkapan_tidur',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Selimut Bayi Motif Polos',
                'description' => 'Selimut bayi berbahan fleece dengan tekstur bulu yang lembut dan hangat. Desain polos dengan pilihan warna netral yang cocok untuk bayi laki-laki maupun perempuan.',
                'price' => 200000,
                'image_path' => 'images/p24.png',
                'category' => 'perlengkapan_lain',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sarung Tidur Bayi Zipper',
                'description' => 'Sarung tidur bayi dengan zipper depan yang memudahkan saat memakaikan. Terbuat dari bahan katun yang lembut dan menyerap keringat. Dilengkapi dengan kaki untuk memberikan kebebasan bergerak bayi saat tidur.',
                'price' => 250000,
                'image_path' => 'images/p25.png',
                'category' => 'perlengkapan_tidur',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gendongan Bayi Ergonomis',
                'description' => 'Gendongan bayi yang didesain ergonomis untuk mendukung postur tubuh bayi. Terbuat dari bahan katun yang nyaman dan breathable. Dilengkapi dengan beberapa posisi gendongan yang dapat disesuaikan.',
                'price' => 350000,
                'image_path' => 'images/p26.png',
                'category' => 'perlengkapan_lain',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Matras Bayi Busa',
                'description' => 'Matras bayi berbahan busa yang empuk dan nyaman. Dilengkapi dengan cover bantal yang dapat dilepas dan dicuci.',
                'price' => 300000,
                'image_path' => 'images/p27.png',
                'category' => 'perlengkapan_tidur',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Set Bedong Bayi Motif Cloud',
                'description' => 'Set bedong bayi yang terdiri dari bedong, bantal, dan selimut dengan motif cloud yang lembut. Terbuat dari bahan katun organik yang aman untuk kulit bayi.',
                'price' => 400000,
                'image_path' => 'images/p28.png',
                'category' => 'perlengkapan_tidur',                
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}

